import DashboardDrivers from "@/components/Drivers/DashboardDrivers";
import Dashboard from "@/components/Home/Dashboard";
import DashboardInvoices from "@/components/Invoices/DashboardInvoices";
import Navbar from "@/components/Navbar";
import DashboardOrders from "@/components/Orders/DashboardOrders";
import DashboardVehicles from "@/components/Vehicles/DashboardVehicles";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter()

  return (
    <div className="moryson_index">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {router.query.path == "home" ? <Dashboard /> : undefined}
      {router.query.path == "orders" ? <DashboardOrders /> : undefined}
      {router.query.path == "vehicles" ? <DashboardVehicles /> : undefined}
      {router.query.path == "drivers" ? <DashboardDrivers /> : undefined}
      {router.query.path == "invoices" ? <DashboardInvoices /> : undefined}
      {router.query.path == "reports" ? <DashboardInvoices /> : undefined}
    </div>
  );
}
