import Dashboard from "@/components/Home/Dashboard";
import Navbar from "@/components/Navbar";
import Room from "@/components/Room/Room";
import Reservation from "@/components/Réservation/Reservation";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter()

  return (
    <div className="hostel_index">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {router.query.path == "home" ? <Dashboard /> : undefined}
      {router.query.path == "room" ? <Room /> : undefined}
      {router.query.path == "reservation" ? <Reservation /> : undefined}
    </div>
  );
}
